# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            MDAnalysis
tagline:          A Python toolkit for the analysis of molecular dynamics simulations.
url:              http://www.mdanalysis.org
paginate:         1
baseurl:          /
author:
  name:           The MDAnalysis Team
  url:            https://twitter.com/mdanalysis

paginate:         5

# Custom vars
version:          0.9.1
github:
  repo:           https://github.com/MDAnalysis/mdanalysis
pypi:
  package:        https://pypi.python.org/pypi/MDAnalysis
  tests:          https://pypi.python.org/pypi/MDAnalysisTests
  docs:           https://pythonhosted.org/MDAnalysis
mailinglists:
  discussion:
    name:         mdnalysis-discussion
    url:          http://groups.google.com/group/mdnalysis-discussion
  developer: 
    name:         developer
    url:          http://groups.google.com/group/mdnalysis-devel
twitter:
  name:           mdanalysis
  url:            https://twitter.com/mdanalysis