# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MDAnalysis
tagline:          A Python toolkit for the analysis of molecular dynamics simulations.
url:              http://www.mdanalysis.org
baseurl:          /
author:
  name:           The MDAnalysis Team
  url:            https://twitter.com/mdanalysis

images:           /public/images/
blog:             /blog/

# see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap

# We currently have our own atom.xml
#  - jekyll-feed

# Blog pagination
paginate_path:   "/blog/page:num/"
paginate:        3

# Custom vars
version:          0.13.0
github:
#  repo:           http://source.mdanalysis.org
  repo:           https://github.com/MDAnalysis/mdanalysis
  docs:           http://devdocs.mdanalysis.org
  issues:         http://issues.mdanalysis.org
  wiki:           http://wiki.mdanalysis.org
pypi:
  package:        http://download.mdanalysis.org
  tests:          https://pypi.python.org/pypi/MDAnalysisTests
  docs:           http://docs.mdanalysis.org
mailinglists:
  discussion:
    name:         mdnalysis-discussion
    url:          http://groups.google.com/group/mdnalysis-discussion
  developer: 
    name:         developer
    url:          http://groups.google.com/group/mdnalysis-devel
twitter:
  name:           mdanalysis
  url:            https://twitter.com/mdanalysis


