# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MDAnalysis
name:             MDAnalysis
tagline:          A Python package for the analysis of molecular dynamics simulations.
description:      A Python package for the analysis of molecular dynamics simulations.
url:              https://www.mdanalysis.org
baseurl:          /
author:
  name:           The MDAnalysis Team
  url:            https://twitter.com/mdanalysis
  email:          mdnalysis-devel@googlegroups.com

images:           /public/images/
data:             /public/data
js:               /js
blog:             /blog/

# see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

# Blog pagination
paginate_path:   "/blog/page:num/"
paginate:        3

# jekyll-feed
# - our previous feed was called atom.xml so we use it instead
#   of the default feed.xml
feed:
  path: atom.xml

# Custom vars
version:          0.16.2

# see also https://help.github.com/articles/repository-metadata-on-github-pages/
# for what GitHub makes available in site.github
github:
  repo:           https://github.com/MDAnalysis/mdanalysis
  docs:           https://www.mdanalysis.org/mdanalysis
  issues:         https://github.com/MDAnalysis/mdanalysis/issues
  wiki:           https://github.com/MDAnalysis/mdanalysis/wiki
pypi:
  package:        https://pypi.python.org/pypi/MDAnalysis
  tests:          https://pypi.python.org/pypi/MDAnalysisTests
  docs:           https://www.mdanalysis.org/docs
mailinglists:
  discussion:
    name:         mdnalysis-discussion
    url:          https://groups.google.com/group/mdnalysis-discussion
  developer: 
    name:         developer
    url:          https://groups.google.com/group/mdnalysis-devel
twitter:
  name:           mdanalysis
  url:            https://twitter.com/mdanalysis


